on: repository_dispatch

jobs:
  update_shards:
    name: release
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: goanpeca/setup-miniconda@v1
        with:
          python-version: 3.7
          channels: conda-forge,defaults
          channel-priority: strict
          show-channel-urls: true
      - name: make release
        shell: bash -l {0}
        run: |
          conda install -y -q git
          git config --global user.name 'conda-forge-daemon'
          git config --global user.email '64793534+conda-forge-daemon@users.noreply.github.com'
          git config --global pull.rebase false

          pushd ..
          git clone --depth=1 https://github.com/regro/repodata-tools.git
          pushd repodata-tools
          conda install -y -q --file requirements.txt
          pip install -e .
          popd
          popd

          make-github-release
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PAT }}
